// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_-Bi9kyeG3LDmJeAJ7xAoXttQQYKo10',
    appId: '1:506702064826:web:6a80994e22a2af0aeaa683',
    messagingSenderId: '506702064826',
    projectId: 'cloudd-cff9a',
    authDomain: 'cloudd-cff9a.firebaseapp.com',
    storageBucket: 'cloudd-cff9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WO_JeizyA3rOOLLk_6LHXNSFEVrgYxk',
    appId: '1:506702064826:android:710959a046056825eaa683',
    messagingSenderId: '506702064826',
    projectId: 'cloudd-cff9a',
    storageBucket: 'cloudd-cff9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCPfe1_8E2x-HYiUuAsvoH9TFVGkyfTlw',
    appId: '1:506702064826:ios:928d570990017d42eaa683',
    messagingSenderId: '506702064826',
    projectId: 'cloudd-cff9a',
    storageBucket: 'cloudd-cff9a.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCPfe1_8E2x-HYiUuAsvoH9TFVGkyfTlw',
    appId: '1:506702064826:ios:928d570990017d42eaa683',
    messagingSenderId: '506702064826',
    projectId: 'cloudd-cff9a',
    storageBucket: 'cloudd-cff9a.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_-Bi9kyeG3LDmJeAJ7xAoXttQQYKo10',
    appId: '1:506702064826:web:682e7226f2a68a33eaa683',
    messagingSenderId: '506702064826',
    projectId: 'cloudd-cff9a',
    authDomain: 'cloudd-cff9a.firebaseapp.com',
    storageBucket: 'cloudd-cff9a.appspot.com',
  );
}
